{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "splunk-api.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "splunk-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  SPLUNK_SEARCH_API_TOKEN: {{ required "secret.searchApiToken is required when secret.create=true" .Values.secret.searchApiToken | quote }}
{{- end }}